language: swift
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="TransitionButton.xcworkspace"
  - IOS_FRAMEWORK_SCHEME="TransitionButton"
  - IOS_SDK=iphonesimulator11.0
  - EXAMPLE_SCHEME="iOS Example"
  matrix:
   - DESTINATION="platform=iOS Simulator,OS=11.0,id=76513A6D-E646-4CD9-B37A-E51C606999CA"  SCHEME="$IOS_FRAMEWORK_SCHEME"      SDK="$IOS_SDK"      POD_LINT="YES"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -workspace "$WORKSPACE" -list

  # Build and test Framework in Debug
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  # Build Framework in ReleaseTest
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c

  # Build Example in Debug if specified
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

  - ruby Tests/CheckCocoaPodsQualityIndexes.rb TransitionButton
